### ISSUE TITLE
C++17: Change consteval to constexpr

### ISSUE THREAD

**Issue by saptarshih** [a4z/astr#2]
diff --git a/include/a4z/astr.hpp b/include/a4z/astr.hpp
index ee11929..dbeb384 100644
--- a/include/a4z/astr.hpp
+++ b/include/a4z/astr.hpp
@@ -149,7 +149,7 @@ namespace a4z {
     return npos;  // Not found
   }
 
-  consteval bool on_windows() {
+  constexpr bool on_windows() {
 #ifdef _WIN32
     return true;
 #else

**Comment by a4z** [comment]
thank you, astr is now (again) a C++17 library
